### PR TITLE
Implement public API

### PR DESCRIPTION
**Pull request by VietAnh1010**
The url of the public API will be `/api/v1/comments/siteId/pageId`.

### CODE REVIEW

**Comment by joulev** [comment]
chotto matte

**Review by joulev — COMMENTED** [review]
Also this will fail CORS. Please fix.

image

**Comment by joulev** [comment]
Don't think there will be many more PRs, nevertheless this should be observed for all future PRs except Dependabot.

> In case the author is a core developer and he worked on the field he is in charge of, code review is not required; however the PR should only be merged after a self-reviewing session after a cool-down (about 3 hours or more) period. &mdash; [CONTRIBUTING.md](https://github.com/joulev/ezkomment/blob/main/CONTRIBUTING.md)

**Comment by VietAnh1010** [comment]
> Also this will fail CORS.

Damn, I should have kept `cors` package. Forgot about `cors`.

**Comment by joulev** [comment]
Don't worry, I created #215, with CORS now.

**Pull request merged**
