### PR TITLE
Update customise page and sample iframe for the new spec

### PR DESCRIPTION
**Pull request by joulev**
The change can be viewed at /app/site/siteName/customise

### CODE REVIEW

**Comment by VietAnh1010** [comment]
I will review later, currently have some business.

**Comment by joulev** [comment]
> I will review later, currently have some business.

Hmm the review request was automated since one of the modified files is in `/pages/api`. It’s more of a temporary route at the moment for the sample iframe to work though, so there shouldn’t be too much for you to review.

In any case, feel free to do so, but I will self-review this and merge accordingly this afternoon.

**Comment by joulev** [comment]
All good, only remaining issue is in #147. Not immediately needed at the moment.

**Comment by joulev** [comment]
In light of this being merged, the `test-customisation-feature` branch is no longer necessary, so it will be deleted. However anyone can always view its final state at https://github.com/joulev/ezkomment/tree/ec21301cdf731a0b7962d3da3587aa146c533385.

**Pull request merged**
