### PR TITLE
Milestone 3 materials

### PR DESCRIPTION
**Pull request by joulev**
* [x] README. IIRC this is the final version of the README
* [x] Poster
* [x] Video
* [x] Project logs

### CODE REVIEW

**Comment by joulev** [comment]
@VietAnh1010 Could you do the video? My computer microphone is shit.

* [Figma prototyping (with some little animation)](https://www.figma.com/proto/zGVcNdL5BYWkxUfJ1XJVy8/ezkomment?page-id=412%3A175&node-id=412%3A815&viewport=445%2C325%2C0.07&scaling=contain&starting-point-node-id=412%3A176&show-proto-sidebar=1)
* [PDF (if you prefer)](https://github.com/joulev/ezkomment/files/9175968/ms3-video.pdf)

**Comment by VietAnh1010** [comment]
@joulev I will do it tomorrow afternoon.

**Comment by VietAnh1010** [comment]
The video content is really similar to MS2 video.

I am concentrating on showing the differences compare to MS2 during the walk through, mainly the embed feature.

Should we talk a little bit more about testing? Our tutor suggest describing in detail the types of testing used during the development process.

**Comment by joulev** [comment]
I am even thinking of removing most slides after the product walkthrough... since with too much content there's no way the video will be short enough.

Testing and similar stuff should be described in the README instead. I added a bit more information there already, but feel free to add some yourself.

**Comment by joulev** [comment]
The Figma has been updated with shorter content, PDF coming soon.

**Comment by VietAnh1010** [comment]
Slide 15 - 18 should be removed. On slide 19, we may add Integration Test.

Or we can create a new slide and add a code snippet about testing in that slide. I want to talk a little bit more about our testing process.

**Comment by joulev** [comment]
Hmm you can [cut out certain PDF pages](https://smallpdf.com/delete-pages-from-pdf) if you want to do so. Or use the modified PDF above which is only 11 pages long.

**Comment by VietAnh1010** [comment]
I mostly want to modify page 19 :|

And what software did you use to record your screen?

**Comment by joulev** [comment]
> I mostly want to modify page 19 :|

Access the (secret) link I DM'd to you to edit the Figma.
> 
> And what software did you use to record your screen?

macOS has a default screen recorder, I think Windows has one too (called Game Bar or something, I've not used Windows for 3yrs+)

**Comment by VietAnh1010** [comment]
I think we need to add more information about our testing process.

For example, I may add:

```markdown
One notable test case for back-end is to ensure statistic for site is updated correctly whenever a new comment is posted.
```

Something like that. (I don't like the "test cases table" in the sample README provide on Telegram. Who care about test cases?). Some example should be enough for other teams to understand what are tested in our project.

I will also add more information about manual API testing using Postman.

**Comment by joulev** [comment]
Yes, please do.

Updated PDF: [ms3-video-v3.pdf](https://github.com/joulev/ezkomment/files/9180535/combinepdf-2.pdf)

**Comment by VietAnh1010** [comment]
Also, do you have any exisiting website? We will need to demonstrate the embed feature.

By adding the <iframe> tag on that website.

**Comment by joulev** [comment]
> Also, do you have any exisiting website? We will need to demonstrate the embed feature.
> 
> By adding the <iframe> tag on that website.

https://ezkdev.joulev.dev/sample/index.html

source at public/sample/index.html

**Comment by VietAnh1010** [comment]
If possible, I want to work on `prod` branch as the embed URL shown in the app only works with `prod` branch.

Let me check the production delopment.

**Comment by joulev** [comment]
Hmm okay let's merge to prod. It's stable enough already anyway.

**Comment by joulev** [comment]
Shipped to prod, after ~3-4 mins of building and ezkomment.joulev.dev will work.

**Comment by VietAnh1010** [comment]
I wish I can cut some part of the video ... just the audio.

And can you access the video now?

**Comment by joulev** [comment]
Yes I can, sorry I had some super-urgent business for the last hour.

Will finish everything now.

**Comment by VietAnh1010** [comment]
If possible, you can go download the video, cut some parts and upload it again.

Please cut "hello", and "hi" when I created a comment in the app demonstration. Why did I say these 2 words with a high note?

**Comment by joulev** [comment]
> If possible, can you download the video, cut some parts and upload it again.
> 
> Please cut "hello", and "hi" when I created a comment in the app demonstration. Why did I say these 2 words with a high note?
> 
> It's fine to keep it tho.

Don't worry this won't be the final version of the video, we will need to submit another in the week before 20 August. I will edit it then (or edit a different video if we make another).

**Comment by VietAnh1010** [comment]
https://drive.google.com/file/d/15DtETTPi_e2nMCnlPB3eU5kr8kfEGImP/view?usp=sharing

MOV file, process much faster.

**Comment by joulev** [comment]
Codecov uploading fails? I say f*ck it, it will be rerun after merging anyway.

**Comment by joulev** [comment]
Don't worry, since the MP4 file has already been processed even before you uploaded the MOV file (yes I tested it)

**Pull request merged**
