### PR TITLE
Fix some problems in current implementation of public API

### PR DESCRIPTION
**Pull request by joulev**
* Code repetition is reduced

* Access control is lifted for `/v1/comments/x/y`. Other routes are still restricted. That's nice.

  image

  (the embed still works cross-domain)

### CODE REVIEW

**Comment by VietAnh1010** [comment]
With this implementation, we will have to do 2 queries for each `GET` request. For each `POST` request, we also query the same document twice (the page, once to check whether it exists and once to get the auto-approve configuration). Quite wasteful.

For CORS, it would be better if we use [dynamic origin](https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin), by attaching the origin after we query the page to check whether it exists. Not very sure whether this is necessary though.

**Review by VietAnh1010 — APPROVED** [review]
Approve (at the moment). I will improve the implementation later on.

**Comment by joulev** [comment]
> For CORS, it would be better if we use [dynamic origin](https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin), by attaching the origin after we query the page to check whether it exists. Not very sure whether this is necessary though.

Since the API is intended to be used everywhere, I think allowing all origins in all cases should be preferred.

**Comment by VietAnh1010** [comment]
The (old) boilerplate implementation only executes 1 query on each request to the public API, but I have to copy the code, which is not a good practice.

I will probably fix that using higher-order functions, for example:

```ts
const createComment = createCommentWith((t, pageRef) => getDocumentInTransaction<Page>(t, pageRef));
const publicCreateComment = createCommentWith((t, pageRef, siteId) => getPageInTransactionWithSiteId(t, pageRef, siteId));
```

**Comment by joulev** [comment]
@VietAnh1010 Wait, but doesn’t that mean `/api/pages/:pid/comments` (from which this code is written) is inefficient too? It is used as the `GET` route in the embed page so it will be used a *lot* more than this public API. I suggest fixing that too.

**Comment by VietAnh1010** [comment]
@joulev I should have elaborated that query here is the number of request we send to Firebase.

`/api/pages/:pid/comments` is efficient, as we only send 1 request to Firebase to get the comments.

For the public API, the current implementation send 2 requests, one to check whether the page exists and one to get the comments. If I use `Transaction`, then I can group the two read operations together into 1 request, and it should improve the API's performance.

**Pull request merged**
